server.port=8083

spring.application.name=ms-rutaexpress-catalog

# -----------------------------------------------------------------------------
# BASE DE DATOS ORACLE
# -----------------------------------------------------------------------------

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

spring.datasource.username=rutaexpress_catalog
spring.datasource.password=RutaExpress123

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true