server.port=8081
spring.application.name=ms-rutaexpress-bff

# =========================
# MICROSERVICIOS
# =========================

# Shipments
shipments.service.url=http://localhost:8080/api/envios

# Catalog
catalog.service.url=http://localhost:8083/api/catalog

# Report
report.service.url=http://localhost:8085/api/report

# Audit
audit.service.url=http://localhost:8084/api/audit


# =========================
# AZURE AD / ENTRA ID
# =========================

# Valida el issuer (iss) del JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d4e45c2c-5598-4953-9517-f1c5f09d4eb1/v2.0

# Valida el audience (aud) del JWT
spring.security.oauth2.resourceserver.jwt.audiences[0]=c515cc67-aed4-4210-89f0-433271797592