server.port=8081
spring.application.name=ms-rutaexpress-bff

# =========================
# MICROSERVICIOS
# =========================

    # Shipments
    shipments.service.url=${SHIPMENTS_SERVICE_URL:http://localhost:8080/api/envios}

    # Catalog
    catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8083/api/catalog}

    # Report
    report.service.url=${REPORT_SERVICE_URL:http://localhost:8085/api/report}

    # Audit
    audit.service.url=${AUDIT_SERVICE_URL:http://localhost:8084/api/audit}


# =========================
# AZURE AD / ENTRA ID
# =========================

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/d4e45c2c-5598-4953-9517-f1c5f09d4eb1/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences[0]=${AZURE_AUDIENCE:c515cc67-aed4-4210-89f0-433271797592}