server.port=8084
spring.application.name=ms-rutaexpress-audit

# ===============================
# ORACLE DATABASE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=rutaexpress_audit
spring.datasource.password=RutaExpress123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.duoc.ms_rutaexpress_audit.*
spring.kafka.consumer.properties.spring.json.value.default.type=com.duoc.ms_rutaexpress_audit.event.ShipmentEvent

app.kafka.topic.shipments-events=shipments.events